# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Syazwan_Robotframework installation and first test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install Robot Framework Library
      run: |
        pip install robotframework
    - name: Install WXPython
      run: |
        pip install wxpython==4.0.7
    - name: Install Selenium Library
      run: |
        pip install --upgrade robotframework-seleniumlibrary
    - name: Install Data Driver
      run: |
        pip install --upgrade robotframework-datadriver[XLS]
    - name: Install web driver
      run: |
        pip install webdrivermanager
        webdrivermanager firefox chrome --linkpath /usr/local/bin
  
  first_test:
    runs-on: windows-latest
    needs:  [build]
    
    steps:  
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Run Robot Framework tests on Windows
      if: matrix.os == 'windows-latest'
      run: |
        inv atest --shard ${{ matrix.shard }}/4 -z true
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Test results
        path: zip_results/output
    - name: Create Distributable Package
      run: |
        inv docs
        inv create-package
    - name: Artifacts download for flaky test analysis
      if: ${{ failure() }}
      # flaky-tests-detection and failures-analysis install is here because dependencies takes long
      # time to install and not needed for the test-install
      run : |
        pip install flaky-tests-detection failures-analysis
        python download_file.py --project  MarketSquare --repo robotframework-browser --token ${{ secrets.GITHUB_TOKEN }}
        inv copy-xunit
    - name: Flaky tests detection
      if: ${{ failure() }}
      run: |
        flaky --junit-files=flip_rate/xunit/ --grouping-option=days --window-size=2 --window-count=5 --top-n=10
    - name: Failures analysis
      if: ${{ failure() }}
      run: |
        failures-analysis ./flip_rate/xunit/
    - name: Package demoapp
      run: |
        inv demo-app
    - uses: actions/upload-artifact@v2
      with:
        name: demoapp
        path: zip_results/demoapp
